project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-9T1C506XN5"
  title: "Bjørn Mo Forum"
  description: "Bjørn Mo Forum is a Doctoral Research Fellow at the Department of Political Science at the University of Oslo. His research focuses on cabinet decision-making and appointments in parliamentary democracies."
  
  page-footer: 
    right: 
      - text: "{{< iconify uiw github >}}"
        href: https://github.com/BjornForum
      - text: "{{< iconify logos bluesky >}}"
        href: https://bsky.app/profile/bjornforum.bsky.social
      - text: "{{< iconify logos linkedin >}}"
        href: https://www.linkedin.com/in/bj%C3%B8rn-mo-forum-b62009190/
      - text: "{{< iconify simple-icons googlescholar >}}"
        href: https://scholar.google.com/citations?user=-W7ni-wAAAAJ&hl=en
      - text: "{{< iconify material-symbols mail >}}"
        href: mailto:b.m.forum@stv.uio.no
        
  navbar:
    background: primary
    search: true

    left:
      - href: index.qmd
        text: "About"
      - href: cv/cv.qmd
        text: "CV"
      - href: research/research.qmd
        text: "Research"
      - href: data/data.qmd
        text: "Data"
      - href: teaching/teaching.qmd
        text: "Teaching"
      - href: blog/blog.qmd
        text: "Blog"

    right:
      - icon: person-workspace
        menu:
        - text: "UiO (nor)"
          href: https://www.sv.uio.no/isv/personer/vit/bjormf/
        - text: "UiO (eng)"
          href: https://www.sv.uio.no/isv/english/people/aca/bjormf

format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true